2021-02-26 delete(ORA-00904: invalid identifier)에러 수정 - lina Cause: java.sql.SQLSyntaxErrorException: ORA-00904: "P_MODIFY_DATE": invalid identifier
; bad SQL grammar []; nested exception is
java.sql.SQLSyntaxErrorException: ORA-00904: "P_MODIFY_DATE": invalid
identifier